# Generated by Django 3.0.4 on 2020-03-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='商品名称')),
                ('stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('sell', models.IntegerField(default=0, verbose_name='出货数量')),
                ('barcode', models.BigIntegerField(unique=True, verbose_name='商品条码')),
            ],
        ),
    ]
