# Generated by Django 3.0.4 on 2020-03-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='barcode',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='商品条码'),
        ),
    ]
