# Generated by Django 2.2.2 on 2020-03-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmpro', '0002_commodity_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='barcode',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='商品条码'),
        ),
    ]
